package Interfaz;

import static Interfaz.InterfazMenu.ArbolGenealogico;
import static Interfaz.InterfazMenu.abuelaMaterna;
import static Interfaz.InterfazMenu.abuelaPaterna;
import static Interfaz.InterfazMenu.abueloMaterno;
import static Interfaz.InterfazMenu.abueloPaterno;
import static Interfaz.InterfazMenu.usuario;
import clases.ListaPersonas;
import clases.Nodo;
import clases.Persona;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rodriguez
 */
public class InterfazArbol extends javax.swing.JFrame {

    public void secciones(Persona persona) {
        GridLayout layout = new GridLayout(0, 3, 30, 30);
        JDialog dialogo = new JDialog();
        JPanel panel = new JPanel();
        panel.setLayout(layout);
        int cantidad = persona.cantidadHijos();
        for (int i = 0; i < cantidad; i++) {
            JLabel label = new JLabel();
            label.setBounds(0, 0, 112, 110);
            label.setText(persona.getHijos().obtenerPersona(i).getpersona().getNombre());
            panel.add(label);
        }
        JScrollPane scroll = new JScrollPane(panel);
        dialogo.getContentPane().add(scroll);
        dialogo.pack();
        dialogo.setSize(300, 200);
        dialogo.setLocationRelativeTo(null);
        dialogo.setResizable(false);
        dialogo.setVisible(true);
    }
    
      public void asignacion(){
        Persona raiz = new Persona("");
        ArbolGenealogico.abuelaPaterno().setPadre(raiz);
        ArbolGenealogico.abuelaMaterno().setPadre(raiz);
        ArbolGenealogico.abueloMaterno().setPadre(raiz);
        ArbolGenealogico.abueloPaterno().setPadre(raiz);
        ArbolGenealogico.setRaiz(raiz);
    }

    public void mostrar() {
        Persona raiz = ArbolGenealogico.getRaiz();
        String padre = ArbolGenealogico.SubirNivelPadre(raiz, 1).getNombre();
        etiquetaPadre.setText(padre);
        String madre = ArbolGenealogico.SubirNivelMadre(raiz, 1).getNombre();
        etiquetaMadre.setText(madre);
        String abueloP = ArbolGenealogico.SubirNivelPadre(raiz, 2).getNombre();
        etiquetaAbueloPaterno.setText(abueloP);
        String abuelaM = ArbolGenealogico.SubirNivelMadre(raiz, 2).getNombre();
        etiquetaAbuelaMaterno.setText(abuelaM);
        String abueloM = ArbolGenealogico.SubirNivelPadre(ArbolGenealogico.SubirNivelMadre(raiz, 1), 1).getNombre();
        etiquetaAbueloMaterno.setText(abueloM);
        String abuelaP = ArbolGenealogico.SubirNivelMadre(ArbolGenealogico.SubirNivelPadre(raiz, 1), 1).getNombre();
        etiquetaAbuelaPaterna.setText(abuelaP);
        etiquetaUsuario.setText(raiz.getNombre());
        String esposa = ArbolGenealogico.obtenerEsposa();
        etiquetaEsposa.setText(esposa);
    }
    
    public void verificarRelacion(Persona persona1, Persona persona2, String relacion){
        if(relacion.equals("Hij@")){
            if(persona1.getPadre() == persona2 && !persona2.getPadre().getNombre().equals("")){
                resultadoEtiqueta.setText("Si lo es");
            }
            else{
                resultadoEtiqueta.setText("No lo es");
            }
        }
        else if(relacion.equals("Padre")){
            if(persona1 == persona2.getPadre()){
                resultadoEtiqueta.setText("Si lo es");
            }
            else{
                resultadoEtiqueta.setText("No lo es");
            }
        }
        else if(relacion.equals("Herman@")){
            if(persona1.getPadre() == persona2.getPadre()){
                resultadoEtiqueta.setText("Si lo es");
            }
            else{
                resultadoEtiqueta.setText("No lo es");
            }
        }
    }

    /**
     * Creates new form IngresarDatos
     */
    public InterfazArbol() {
        initComponents();
        setTitle("Arbol Genealógico");
        
        mostrar();
        jPanel18.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        etiquetaHijo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        etiquetaEsposa = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        etiquetaUsuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        etiquetaAbueloPaterno = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        etiquetaAbuelaPaterna = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        etiquetaHermano1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        etiquetaMadre = new javax.swing.JLabel();
        BotonVolver = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        etiquetaPadre = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        etiquetaAbueloMaterno = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        etiquetaAbuelaMaterno = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jPanel18 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        resultadoEtiqueta1 = new javax.swing.JLabel();
        resultadoEtiqueta = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(890, 600));
        setPreferredSize(new java.awt.Dimension(890, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(70, 23, 116));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(0, 204, 0));
        jPanel13.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaHijo1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        etiquetaHijo1.setText("Hijos");
        etiquetaHijo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiquetaHijo1MouseClicked(evt);
            }
        });
        jPanel13.add(etiquetaHijo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("V");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, -1, -1));

        jPanel14.setBackground(new java.awt.Color(0, 204, 0));
        jPanel14.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaEsposa.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        etiquetaEsposa.setText("Esposa");
        jPanel14.add(etiquetaEsposa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, -1, -1));

        jPanel15.setBackground(new java.awt.Color(0, 204, 0));
        jPanel15.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaUsuario.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        etiquetaUsuario.setText("Usuario");
        jPanel15.add(etiquetaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel4.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaAbueloPaterno.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        etiquetaAbueloPaterno.setText("Abuelo");
        jPanel1.add(etiquetaAbueloPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaAbuelaPaterna.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        etiquetaAbuelaPaterna.setText("Abuela");
        jPanel2.add(etiquetaAbuelaPaterna, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jPanel6.setBackground(new java.awt.Color(0, 204, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaHermano1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        etiquetaHermano1.setText("Hermanos");
        etiquetaHermano1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiquetaHermano1MouseClicked(evt);
            }
        });
        jPanel6.add(etiquetaHermano1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("V");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 204, 0));
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaMadre.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        etiquetaMadre.setText("Madre");
        jPanel7.add(etiquetaMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        BotonVolver.setText("Volver");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        jPanel4.add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel8.setBackground(new java.awt.Color(0, 204, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaPadre.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        etiquetaPadre.setText("Padre");
        jPanel8.add(etiquetaPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jPanel12.setBackground(new java.awt.Color(0, 204, 0));
        jPanel12.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaAbueloMaterno.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        etiquetaAbueloMaterno.setText("Abuelo");
        jPanel12.add(etiquetaAbueloMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 40, -1, -1));

        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jButton1.setText("Verificar relaciones");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 204, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaAbuelaMaterno.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        etiquetaAbuelaMaterno.setText("Abuela");
        jPanel5.add(etiquetaAbuelaMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 40, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 20, 20));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 150, 30));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 20, 20));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 20, 20));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 20, 20));
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 310, 30));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 20, 20));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 20, 20));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 20, 90));

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 20, 20));
        jPanel4.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 150, 30));

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 20, 20));

        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 20, 40));
        jPanel4.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 150, 30));

        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 20, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 900, 600));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jButton3.setText("Volver a ver el arbol");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel18.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jPanel18.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 180, -1));

        jComboBox2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hij@", "Padre", "Herman@" }));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jPanel18.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jComboBox3.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jComboBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox3MouseClicked(evt);
            }
        });
        jPanel18.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 210, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel6.setText("Es");
        jPanel18.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel7.setText("De");
        jPanel18.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        resultadoEtiqueta1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        resultadoEtiqueta1.setText("Respuesta");
        jPanel18.add(resultadoEtiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        resultadoEtiqueta.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        resultadoEtiqueta.setText("Respuesta");
        jPanel18.add(resultadoEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        jButton4.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jButton4.setText("Verificar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel18.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        getContentPane().add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new InterfazMenu().setVisible(true);
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void etiquetaHermano1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaHermano1MouseClicked
        secciones(ArbolGenealogico.getRaiz().getPadre());
    }//GEN-LAST:event_etiquetaHermano1MouseClicked

    private void etiquetaHijo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaHijo1MouseClicked
        secciones(ArbolGenealogico.getRaiz());
    }//GEN-LAST:event_etiquetaHijo1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jPanel18.setVisible(true);
        jPanel4.setVisible(false);
        asignacion();
        ListaPersonas lista = ArbolGenealogico.encontrarPersonas();
        for(int i = 0; i<lista.getLargo(); i++){
            String valor = lista.obtenerPersona(i).getpersona().getNombre();
            jComboBox1.addItem(valor);
            jComboBox3.addItem(valor);
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        jPanel18.setVisible(false);
        jPanel4.setVisible(true);
        ArbolGenealogico.setRaiz(usuario);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        Persona Persona1 = ArbolGenealogico.buscarPersona(jComboBox1.getSelectedItem().toString().trim());
        Persona Persona2 = ArbolGenealogico.buscarPersona(jComboBox3.getSelectedItem().toString().trim());
        String relacion = jComboBox2.getSelectedItem().toString().trim();
        verificarRelacion(Persona1, Persona2, relacion);
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        Persona Persona1 = ArbolGenealogico.buscarPersona(jComboBox1.getSelectedItem().toString().trim());
        Persona Persona2 = ArbolGenealogico.buscarPersona(jComboBox3.getSelectedItem().toString().trim());
        String relacion = jComboBox2.getSelectedItem().toString().trim();
        verificarRelacion(Persona1, Persona2, relacion);
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jComboBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MouseClicked
        Persona Persona1 = ArbolGenealogico.buscarPersona(jComboBox1.getSelectedItem().toString().trim());
        Persona Persona2 = ArbolGenealogico.buscarPersona(jComboBox3.getSelectedItem().toString().trim());
        System.out.println(Persona1.getNombre());
        System.out.println(Persona2.getNombre());
        String relacion = jComboBox2.getSelectedItem().toString().trim();
        verificarRelacion(Persona1, Persona2, relacion);
    }//GEN-LAST:event_jComboBox3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        Persona Persona1 = ArbolGenealogico.buscarPersona(jComboBox1.getSelectedItem().toString().trim());
        Persona Persona2 = ArbolGenealogico.buscarPersona(jComboBox3.getSelectedItem().toString().trim());
        String relacion = jComboBox2.getSelectedItem().toString().trim();
        verificarRelacion(Persona1, Persona2, relacion);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        secciones(ArbolGenealogico.getRaiz().getPadre());
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        secciones(ArbolGenealogico.getRaiz());
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonVolver;
    private javax.swing.JLabel etiquetaAbuelaMaterno;
    private javax.swing.JLabel etiquetaAbuelaPaterna;
    private javax.swing.JLabel etiquetaAbueloMaterno;
    private javax.swing.JLabel etiquetaAbueloPaterno;
    private javax.swing.JLabel etiquetaEsposa;
    private javax.swing.JLabel etiquetaHermano1;
    private javax.swing.JLabel etiquetaHijo1;
    private javax.swing.JLabel etiquetaMadre;
    private javax.swing.JLabel etiquetaPadre;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel resultadoEtiqueta;
    private javax.swing.JLabel resultadoEtiqueta1;
    // End of variables declaration//GEN-END:variables
}
